name: Dev Branch Update

on:
  push:
    branches:
    - main

jobs:
  dev_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Update version
      run: hemtt script update_patch
    - name: Run HEMTT release
      run: hemtt release
    - name: Upload to Steam
      uses: arma-actions/workshop-upload@v1
      with:
        appId: "107410"
        itemId: "3312012350"
        contentPath: "releases/haf-latest/@haf"
        changelog: "Automatic dev build update"
      env:
        STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
        STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}