name: Dev Branch Update

on:
  push:
    branches:
    - main

jobs:
  dev_update:
    runs-on: ubuntu-latest
    steps:
        # - name: Set VERSION env
        #   run: echo VERSION=${GITHUB_REF:11} >> $GITHUB_ENV
        - name: Checkout the source code
          uses: actions/checkout@v2
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release --no-archive
        - name: Move release to releases folder
          run:
            mv .hemttout/release "@haf"
        - name: Zip release
          run: zip -r "@haf.zip" ./@haf
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: ./@haf.zip
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Update to Steam Workshop (stable)
          uses: arma-actions/workshop-upload@v1
          with:
            itemId: '3312012350'
            contentPath: './@haf'
          env:
            STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
            STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}